### PR TITLE
Create swap-hue

### PR DESCRIPTION
**Pull request by paskino**
Color filter that makes a 180 degrees rotation of the hue.

### CODE REVIEW

**Comment by soreau** [comment]
@paskino Thanks for taking the time to submit this patch. Everything looks good except the commit message line lengths should be kept to somewhere between 50-80 characters long. We don't have patch submission instructions anywhere but this is a common expectation for any git commit. See the difference between [these](https://github.com/compiz-reloaded/compiz/commit/5e9d73697d0c1f570245140ae390920f6973640c) [two](https://github.com/compiz-reloaded/compiz-plugins-main/pull/14/commits/14bb0c7844cba4b3fe141467626ee7c533eedd72) commit messages for example.

**Comment by paskino** [comment]
So how do I do this?
I've updated my initial comment. Is that enough?

**Comment by soreau** [comment]
The easiest way is probably to delete the repo and re-fork it

**Comment by soreau** [comment]
Everything should be working now.

**Pull request closed without merging**
